use meuprontuario;

DROP TABLE IF EXISTS ESPECIALIDADE;
DROP TABLE IF EXISTS MEDICO;

-- Tabela Endereco
CREATE TABLE ENDERECO (
    ID_ENDERECO INT AUTO_INCREMENT NOT NULL,
    LOGRADOURO VARCHAR(150) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    PRIMARY KEY (ID_ENDERECO)
);

-- Tabela Hospital
CREATE TABLE HOSPITAL (
    ID_HOSPITAL INT AUTO_INCREMENT NOT NULL,
    RAZAO_SOCIAL VARCHAR(150) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    PRIMARY KEY (ID_HOSPITAL),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO) ON DELETE CASCADE
);

-- Tabela Especialidade
CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE INT AUTO_INCREMENT NOT NULL,
    NOME_ESPECIALIDADE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_ESPECIALIDADE)
);

-- Tabela Paciente
CREATE TABLE PACIENTE (
    ID_PACIENTE INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    PRIMARY KEY (ID_PACIENTE),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO) ON DELETE CASCADE
);

-- Tabela Medico
CREATE TABLE MEDICO (
    ID_MEDICO INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    CONSELHO VARCHAR(50) NOT NULL,
    ID_HOSPITAL INT NOT NULL,
    ID_ESPECIALIDADE INT NOT NULL,
    PRIMARY KEY (ID_MEDICO),
    FOREIGN KEY (ID_HOSPITAL) REFERENCES HOSPITAL(ID_HOSPITAL) ON DELETE CASCADE,
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE) ON DELETE CASCADE
);
